version: '2'
services:
#  nginx:
#    image: nginx:1.15.1-alpine
#    ports:
#      - 10080:80
#    depends_on:
#      - api
#      - web
#    volumes:
#      - ./docker/config/nginx.dev.conf:/etc/nginx/conf.d/default.conf
#  api:
#    build:
#      context: api
#      dockerfile: Dockerfile.dev
#    user: apiuser
#    ports:
#      - 19000:9000
#    volumes:
#      - .:/timeline
#    depends_on:
#      - mysql
#      - elasticsearch
#    environment:
#      DB_HOST: mysql
  mysql:
    image: mysql:5.7.22
    command: --disable-partition-engine-check
#    ports:
#      - 13306:3306
    volumes:
      - dbdata1:/var/lib/mysql
    env_file:
      - config/docker-env.ini
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: timeline
      MYSQL_USER: timeline_user
  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    environment:
      discovery.type: single-node
#  web:
#    build:
#      context: web
#      dockerfile: Dockerfile.dev
#    ports:
#      - 14200:4200
#    volumes:
#      - .:/timeline
volumes:
  esdata1:
    driver: local
  dbdata1:
    driver: local

