version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - web
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - apistorage:/apidist/storage
      - webdist:/webdist
    env_file:
      - ./etc/docker/web.env
      - ./etc/docker/api.env
    networks:
      - internal
  api:
    build:
      context: api
      dockerfile: Dockerfile
    user: apiuser
    volumes:
      - apistorage:/apidist/storage
      - ./api/.env:/apidist/.env
    env_file:
      - ./etc/docker/mysql.env
      - ./etc/docker/api.env
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - internal
  mysql:
    image: mysql:5.7.22
    command: --disable-partition-engine-check
    ports:
      - 13306:3306
    volumes:
      - dbdata1:/var/lib/mysql
    env_file:
      - ./etc/docker/mysql.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: timeline
      MYSQL_USER: timeline_user
    networks:
      - internal
  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - internal
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - webdist:/webdist
volumes:
  esdata1:
    driver: local
  dbdata1:
    driver: local
  webdist:
    driver: local
  apistorage:
    driver: local

networks:
  internal: