apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      name: api-pod
      labels:
        component: api
    spec:
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-storage-pvc
        - name: backup
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: nginx-config
          configMap:
            name: api-nginx-cm
        - name: api-env
          configMap:
            name: api-cm
      containers:
        - name: api
          image: moail/timeline-api
          securityContext:
            runAsGroup: 1500
            runAsUser: 1500
          volumeMounts:
            - name: api-storage
              mountPath: /api/storage/app
            - name: backup
              mountPath: /backup
            - name: api-env
              mountPath: /api/.env
              subPath: .env
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: api-storage
              mountPath: /api/storage/app
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
