apiVersion: v1
kind: ConfigMap
metadata:
  name: api-nginx-cm
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
