apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon-deployment
spec:
  selector:
    matchLabels:
      component: horizon
  template:
    metadata:
      name: horizon-pod
      labels:
        component: horizon
    spec:
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-storage-pvc
        - name: backup
          persistentVolumeClaim:
            claimName: backup-pvc
      containers:
        - name: horizon
          image: moail/timeline-api
          readinessProbe:
            exec:
              command:
                - php
                - artisan
                - check:health
          livenessProbe:
            exec:
              command:
                - php
                - artisan
                - check:health
          envFrom:
            - configMapRef:
                name: api-cm
            - secretRef:
                name: api-secret
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          securityContext:
            runAsGroup: 1500
            runAsUser: 1500
          command:
            - php
          args:
            - artisan
            - horizon
          volumeMounts:
            - name: api-storage
              mountPath: /api/storage/app
            - name: backup
              mountPath: /backup
