apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
spec:
  selector:
    matchLabels:
      component: scheduler
  template:
    metadata:
      name: scheduler-pod
      labels:
        component: scheduler
    spec:
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-storage-pvc
        - name: backup
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: api-env
          configMap:
            name: api-cm
      containers:
        - name: scheduler
          image: moail/timeline-api
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          command:
            - crond
          args:
            - -f
          volumeMounts:
            - name: api-storage
              mountPath: /api/storage/app
            - name: backup
              mountPath: /backup
            - name: api-env
              mountPath: /api/.env
              subPath: .env
