apiVersion: v1
kind: ConfigMap
metadata:
  name: api-cm
data:
  .env: |
    APP_NAME: Timeline
    APP_ENV: local
    APP_KEY: base64:/Xvc9R/S1Q5dQ7ViD7YvID3AF0vyXl0qYkxL4yyjHKo=
    APP_DEBUG: true
    APP_URL: https://api.timeline.localhost

    APP_TIMEZONE: America/New_York
    APP_BACKUP: true

    LOG_CHANNEL: stack

    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: timeline
    DB_USERNAME: timeline_user
    DB_PASSWORD: timeline_user_pwd

    DEFAULT_DATE_ATTRIBUTE: Year

    TIMEZONE: America/New_York

    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9200
    ELASTICSEARCH_SCHEME: http

    REDIS_HOST: queue
    QUEUE_CONNECTION: redis

    JWT_SECRET: 9F8bu3XVifPfPIlkCd5TFwf2PxzOmEou