apiVersion: v1
kind: ConfigMap
metadata:
  name: api-cm
data:
  APP_NAME: Timeline
  APP_ENV: local
  APP_KEY: base64:/Xvc9R/S1Q5dQ7ViD7YvID3AF0vyXl0qYkxL4yyjHKo=
  APP_DEBUG: "true"
  APP_URL: https://api.timeline.test

  APP_TIMEZONE: America/New_York
  APP_BACKUP: "true"

  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: db-cluster-ip-service
  DB_PORT: "3306"

  DEFAULT_DATE_ATTRIBUTE: Year

  TIMEZONE: America/New_York

  ELASTICSEARCH_HOST: search-engine-cluster-ip-service
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_SCHEME: http
  CACHE_DRIVER: redis

  SESSION_DRIVER: redis
  SESSION_CONNECTION: session

  REDIS_HOST: queue-cluster-ip-service
  QUEUE_CONNECTION: redis

  JWT_SECRET: 9F8bu3XVifPfPIlkCd5TFwf2PxzOmEou
