apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - timeline.test
        - api.timeline.test
  rules:
    - host: api.timeline.test
      http:
        paths:
          - path: /
            backend:
              serviceName: api-cluster-ip-service
              servicePort: api-port
    - host: timeline.test
      http:
        paths:
          - path: /
            backend:
              serviceName: web-cluster-ip-service
              servicePort: web-port
