FROM node:alpine as build-web
RUN npm install -g @angular/cli

WORKDIR /src
COPY . /src
RUN mkdir -p /dist
RUN npm install && rm -f /dist/* && ng build --aot --prod --output-path=/dist

FROM nginx:1.15.1-alpine
COPY --from=build-web /dist /usr/share/nginx/html