FROM php:7.2.13-cli-alpine3.8

# Configure PHP

RUN apk update && apk add build-base \
  wget \
  curl \
  git \
  grep \
  zlib-dev \
  zip \
  freetype-dev \
  libjpeg-turbo-dev \
  libpng-dev \
  sudo \
  bash \
  autoconf

RUN docker-php-ext-install mysqli mbstring pdo pdo_mysql tokenizer pcntl
RUN docker-php-ext-configure gd --with-gd --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

WORKDIR /apidist
COPY . /apidist

CMD ["php", "artisan", "horizon"]