FROM moail/timeline-api

RUN rm -rf /api/*

USER tlmgr
COPY --chown=tlmgr:tlmgr ./composer.json /api/composer.json
COPY --chown=tlmgr:tlmgr ./composer.lock /api/composer.lock
RUN composer config --global repos.packagist composer https://packagist.org
RUN composer install --no-scripts --no-autoloader

COPY --chown=tlmgr:tlmgr . /api
RUN composer install
