FROM node:10.6.0-alpine

RUN apk update && apk add build-base \
  sudo \
  bash

RUN npm install -g @angular/cli

WORKDIR /webdist
COPY . /webdist

RUN npm install

CMD ["ng", "serve", "--ssl", "--host", "0.0.0.0"]
